---
title: Market Trends
author: Eric Patterson
date: \today
header-includes:
- \usepackage{float}
- \usepackage{wrapfig}
- \usepackage{graphicx}
- \usepackage{titlesec}
- \usepackage{subcaption}
- \usepackage{bbm}
---

```{r setup, include=FALSE, purl=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo=FALSE)
# devtools::dev_mode(on=TRUE) # currently quantmod and largescalemomentum are not on master
library(xts)
library(data.table)
library(ggplot2)
# library(largescalemomentum)
source('plot-tools.R')
```

## Trends in Selected Symbols

```{r data, echo=FALSE, message=FALSE, warning=FALSE}
symbol_file <- file.path('~','Documents','data','my_symbols.csv')
symbols <- fread(symbol_file)
# hide_data <- symbols[, plot_with_ma(symbol, start_date), by = symbol] #gets the labelling wrong...why?
# hide_data <- lapply(symbols[,symbol], function(x) { plot_with_ma(x, symbols[symbol == x, start_date])})
data <- rbindlist( lapply(symbols[, symbol], function(x) load_with_ma(x,
symbols[symbol==x, start_date])))
```

```{r data, echo=FALSE, message=FALSE, warning=FALSE}
unique_symbols <- symbols[, symbol]
data[, symbol_f := factor(symbol, levels=unique_symbols)]  # Fix the ordering of the symbols so that facet_grid doesn't reorder alphabetically
adjusted <- data[price_type=='adjusted',]
symbols_per_page <- 3
symbol_start <- seq(1, length(unique_symbols), by=symbols_per_page)
for( j in symbol_start) {
	next_symbols <- unique_symbols[j:(j+symbols_per_page-1)]
	next_adjusted <- adjusted[ symbol %in% next_symbols,]
	next_plot <- ggplot(next_adjusted, aes(Date,value,color=as.factor(window))) +
		facet_grid(symbol_f ~ ., scales = "free_y") +  # , space="free_y") + possibly useful if they are all on the same scale
		geom_step()
	print(next_plot)
}
```
